version: '2.34'

include:
  - ../backend/docker-compose.yml

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
        required: true
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 --spider http://localhost:3000/api/health"]
      start_period: 10s
      interval: 2s
      retries: 2
      timeout: 5s